name: Dotty CI

on:
  push:
  pull_request:

jobs:
  good:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo "Hello"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.ref = ${{ github.event.ref }}"
          echo "startsWith(github.event.ref, 'refs/tags/') = ${{ startsWith(github.event.ref, 'refs/tags/') }}"
          echo "If-condition = ${{ (github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')) || github.event_name == 'schedule' }}"

  bad:
    runs-on: ubuntu-latest
    if: (
          github.event_name == 'push' &&
          startsWith(github.event.ref, 'refs/tags/')
        ) ||
        github.event_name == 'schedule'

    steps:
      - name: Test
        run: echo "Hello"
